-- MySQL Script generated by MySQL Workbench
-- 08/19/14 20:49:36
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_network` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `social_network` ;

-- -----------------------------------------------------
-- Table `social_network`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`user` ;

CREATE TABLE IF NOT EXISTS `social_network`.`user` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `phone` INT NULL,
  `job_place_x` DOUBLE NULL,
  `job_place_y` DOUBLE NULL,
  `admin` TINYINT(1) NULL,
  `deleted` TINYINT(1) NULL,
  INDEX `name` (`name` ASC),
  INDEX `sector` (`sector` ASC),
  INDEX `country` (`country` ASC),
  INDEX `email` (`email` ASC),
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`media` ;

CREATE TABLE IF NOT EXISTS `social_network`.`media` (
  `id_media` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(8) NULL,
  `path` VARCHAR(200) NULL,
  `deleted` TINYINT(1) NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_media`),
  INDEX `fk_media_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_media_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `social_network`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`wall_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`wall_entry` ;

CREATE TABLE IF NOT EXISTS `social_network`.`wall_entry` (
  `id_wall_entry` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `message` VARCHAR(500) NULL,
  `like_count` INT NULL,
  `visibility` VARCHAR(7) NULL,
  `link1` INT NULL,
  `link2` INT NULL,
  `link3` INT NULL,
  `deleted` TINYINT(1) NULL,
  `email_owner` VARCHAR(45) NOT NULL,
  `email_poster` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_wall_entry`),
  INDEX `fk_wall_entry_user1_idx` (`email_owner` ASC),
  INDEX `fk_wall_entry_user2_idx` (`email_poster` ASC),
  CONSTRAINT `fk_wall_entry_user1`
    FOREIGN KEY (`email_owner`)
    REFERENCES `social_network`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wall_entry_user2`
    FOREIGN KEY (`email_poster`)
    REFERENCES `social_network`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`like_wall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`like_wall` ;

CREATE TABLE IF NOT EXISTS `social_network`.`like_wall` (
  `user_email` VARCHAR(45) NOT NULL,
  `id_wall_entry` INT NOT NULL,
  PRIMARY KEY (`user_email`, `id_wall_entry`),
  INDEX `fk_like_user1_idx` (`user_email` ASC),
  INDEX `fk_like_wall_entry1_idx` (`id_wall_entry` ASC),
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `social_network`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_wall_entry1`
    FOREIGN KEY (`id_wall_entry`)
    REFERENCES `social_network`.`wall_entry` (`id_wall_entry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`comment` ;

CREATE TABLE IF NOT EXISTS `social_network`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  `like_count` INT NULL,
  `deleted` TINYINT(1) NULL,
  `id_wall_entry` INT NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comment_entry_wall_entry1_idx` (`id_wall_entry` ASC),
  INDEX `fk_comment_entry_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_comment_entry_wall_entry1`
    FOREIGN KEY (`id_wall_entry`)
    REFERENCES `social_network`.`wall_entry` (`id_wall_entry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_entry_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `social_network`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`friendhsip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`friendhsip` ;

CREATE TABLE IF NOT EXISTS `social_network`.`friendhsip` (
  `email_adder` VARCHAR(45) NOT NULL,
  `email_added` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email_adder`, `email_added`),
  INDEX `fk_user_has_user_user1_idx` (`email_added` ASC),
  INDEX `fk_user_has_user_user_idx` (`email_adder` ASC),
  CONSTRAINT `fk_user_has_user_user`
    FOREIGN KEY (`email_adder`)
    REFERENCES `social_network`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`email_added`)
    REFERENCES `social_network`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`like_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`like_comment` ;

CREATE TABLE IF NOT EXISTS `social_network`.`like_comment` (
  `user_email` VARCHAR(45) NOT NULL,
  `id_comment` INT NOT NULL,
  PRIMARY KEY (`user_email`, `id_comment`),
  INDEX `fk_user_has_comment_entry_comment_entry1_idx` (`id_comment` ASC),
  INDEX `fk_user_has_comment_entry_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_user_has_comment_entry_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `social_network`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_comment_entry_comment_entry1`
    FOREIGN KEY (`id_comment`)
    REFERENCES `social_network`.`comment` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
